# Generated by Django 5.2.14 on 2026-05-27 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgriculturalMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('machine_type', models.CharField(choices=[('tractor', 'Трактор'), ('harvester', 'Комбайн'), ('plow', 'Плуг'), ('seeder', 'Сеялка')], max_length=20, verbose_name='Тип')),
                ('status', models.CharField(choices=[('active', 'В работе'), ('maintenance', 'На ТО'), ('repair', 'В ремонте'), ('inactive', 'Неактивна')], default='active', max_length=20, verbose_name='Статус')),
                ('fuel_type', models.CharField(max_length=50, verbose_name='Тип топлива')),
                ('engine_hours', models.FloatField(default=0.0, verbose_name='Моточасы')),
                ('manufacture_year', models.IntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('routine', 'Плановое ТО'), ('repair', 'Ремонт'), ('inspection', 'Инспекция'), ('seasonal', 'Сезонное обслуживание')], max_length=20, verbose_name='Тип работ')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('status', models.CharField(choices=[('scheduled', 'Запланировано'), ('in_progress', 'В процессе'), ('completed', 'Выполнено'), ('cancelled', 'Отменено')], default='scheduled', max_length=20, verbose_name='Статус')),
                ('scheduled_date', models.DateField(verbose_name='Дата ТО')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='api_v1.agriculturalmachine', verbose_name='Техника')),
            ],
        ),
    ]
